spring.application.name=OAuth2

# --- Google OAuth2 Configuration ---
# Redirect URI: http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-id=your-google-client-id
spring.security.oauth2.client.registration.google.client-secret=your-google-client-secret
spring.security.oauth2.client.registration.google.scope=profile,email

# --- GitHub OAuth2 Configuration ---
# Redirect URI: http://localhost:8080/login/oauth2/code/github
spring.security.oauth2.client.registration.github.client-id=Ov23ctObmAbHfl1yhk0b
spring.security.oauth2.client.registration.github.client-secret=70f1b5e120b6ca8331bed68a93d77a88f17de4dc
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# --- LinkedIn OAuth2 Configuration ---
# Redirect URI: http://localhost:8080/login/oauth2/code/linkedin
spring.security.oauth2.client.registration.linkedin.client-id=your-linkedin-client-id
spring.security.oauth2.client.registration.linkedin.client-secret=your-linkedin-client-secret
spring.security.oauth2.client.registration.linkedin.scope=openid,profile,email

# authorization call back url  http://localhost:8080/login/oauth2/code/github
