spring.application.name=Spring-Security
spring.security.user.name =Aryan
# user name for the web
spring.security.user.password =Aryan2005@
#password for the web
# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/usernameandpassword
spring.datasource.username=root
spring.datasource.password=Aryan2005@

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
